### PR TITLE
Updated JSON display configs.

### PR DESCRIPTION
**Pull request by DuFF14**
Moved updated display configs from Unity repo.

### CODE REVIEW

**Comment by rpavlik** [comment]
So a few notes:

- Key names are inconsistent in style: typically json uses camelCase because that's the Javascript convention. You've got a mix of initial caps and snake_case.
- Unclear whether the version field refers to version of the config file or version of the hardware. In the device descriptor it's version of the config file.

I'll make a file with general updates elsewhere - those are just the changes I noticed in this pull request.

**Comment by rpavlik** [comment]
Oh, and you may want to use Atom or a similar web-savvy editor for editing JSON

**Comment by DuFF14** [comment]
I wasn't sure about Json version number because the existing configs left that field empty or have something like "landscape". I am installing Atom so I will go through and make things consistent. I figured since version is in the "device" field that it referred to the hardware version.

Should there be a config(s) for Oculus in this directory, or does that belong in the Oculus repo?

**Comment by yboger** [comment]
Yes, there should be a config for Oculus.

Yuval

**Comment by rpavlik** [comment]
but the display descriptor, just like the device descriptor, belongs in the Oculus repo - since the config file that would refer to it is there, and eventually that plugin will have it embedded within it.

**Comment by rpavlik** [comment]
Since this format is in flux, can we get a schema version number in here?

**Comment by DuFF14** [comment]
Added schema version number.
These files would be parsed correctly in the DisplayConfig Unity branch: https://github.com/OSVR/OSVR-Unity/pull/41

**Comment by rpavlik** [comment]
I'm going to close this request, since the non-cosmetic changes were just merged in a different pull request.

**Pull request closed without merging**
