### PR TITLE
Added the current working directory to the plugin search path.

### PR DESCRIPTION
**Pull request by JeroMiya**
Specifically, the current working directory plus the OSVR_PLUGIN_DIR predefine subpath, and only if the CWD is not the same as the root (to avoid duplicate paths).

cc: https://github.com/OSVR/OSVR-Core/issues/208

### CODE REVIEW

**Comment by rpavlik** [comment]
I think this looks OK to me - potential security stuff any time you change where we might run code from, but the code isn't being run with any special privilege so it should be OK.

**Comment by JeroMiya** [comment]
Hmm.. good point on security. This might be an issue if they put osvr_server somewhere in the PATH and start it up from some random place in their file system. Should we put a "Don't do that" somewhere in the docs?

**Comment by rpavlik** [comment]
Or, if this is needed for a particular platform, just ifdef it. There are other ifdefs in there as well already.

**Comment by JeroMiya** [comment]
Good call. It now only adds the CWD on Android, and we'll punt for other platforms (not needed yet).

**Pull request merged**
