### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by rpavlik**
Small cleanup of things seen when building on Linux with Clang 6.0. (Plus one or two things that I just noticed could be improved as drive-by fixes)

I should try this on Windows before merging it, in theory.

### CODE REVIEW

**Comment by godbyk** [comment]
`= default` could be declared in the headers unless you want to hide the implementation. 

Otherwise, it looks good to me on first read through. I haven't actually tested it.

**Comment by rpavlik** [comment]
Have to hide the implementation to ensure the destruction happens within a dll, not in its consumer - for the same reason that the constructor and factory func are hidden. Mainly a very sneaky windows bug.

**Comment by rpavlik** [comment]
OK, this has been rebased, so travis should work now. Still haven't tried Windows (and AppVeyor isn't set up right)

**Comment by rpavlik** [comment]
OK, doesn't appear to break Windows, so merging.

**Pull request merged**
