### PR TITLE
Predictive tracking filter

### PR DESCRIPTION
**Pull request by russell-taylor**
This adds an an analysis filter that wraps a VRPN dead-reckoning orientation tracker and provides a way to attach it to any existing orientation-producing tracking device.  Includes an example config file that puts an additional time-parameterized predictive tracker on the OSVR HDK.

### CODE REVIEW

**Comment by russell-taylor** [comment]
I think this is ready to merge.  Will probably do so before too long so we can get this to a customer to test.

**Comment by russell-taylor** [comment]
It looks like the build failures on the ci/push failed because the are running both osx and linux on every machine; one fails on some and the other fails on others.  Not certain about this, but that's what it looks like from the error messages.  Don't want to merge in a broken set of code, so will let someone else take a look at this and will build things from the branch in the meantime.

**Comment by russell-taylor** [comment]
The logs are not helping me figure out why the build is failing.  There does not appear to be any cmake or compiler output included in the error logs, just a report of failure after 0 seconds.  Any help pointing me to how to figure this out appreciated.

**Comment by godbyk** [comment]
The builds on the Travis CI server is complaining that it can't find VRPN.

Instead of building against an external VRPN, can you build against the vendored-vrpn?

**Comment by russell-taylor** [comment]
Kevin, thanks for the fix.  Can you teach me where to look so I can find it myself next time?  The log files I saw just said that the build failed on one or the other operating system.

**Comment by russell-taylor** [comment]
Passes build tests and passes tests with both OSVR HDK and another vendor's HMD, so going ahead and merging ahead of the demo tomorrow.

**Comment by godbyk** [comment]
@russell-taylor Sure. When you click through to the Travis CI details link, it'll take you to the failed jobs page (like this <https://travis-ci.org/OSVR/OSVR-Core/builds/108879430>). From there, you can click on one of the failed job numbers in the table to see the terminal output of the build (e.g., <https://travis-ci.org/OSVR/OSVR-Core/jobs/108879431>). You can usually find the relevant error messages in the terminal output. In this case, it was the messages from CMake complaining: `Could NOT find VRPN (missing: VRPN_LIBRARY VRPN_INCLUDE_DIR)`.

**Pull request merged**
