### PR TITLE
Fixes for issues #127 & #139

### PR DESCRIPTION
**Pull request by janoc**
These two commits fix issues #127 and #139

### CODE REVIEW

**Comment by rpavlik** [comment]
Note: should check to ensure that `m_host` is not empty before doing this, though I think m_host being non-empty is a class invariant (don't know if it's documented or tested as one though)

**Comment by janoc** [comment]
I have tested the case when no host is provided (the default use case with collocated server & client) and it seems to work fine.

**Comment by rpavlik** [comment]
Thanks. Trying to figure out if we put the extra constructor method in a separate library or just say not to use it in the docs, since I don't really think we want game engines using that constructor, but that's all that is blocking the merge

**Comment by janoc** [comment]
Um, why you don't want the game engines use that constructor (the one supplying the host name)? That is a very common use case. If OSVR is meant to be only for localhost and any other use cases unsupported, then *that* is actually going to be a problem.

**Comment by rpavlik** [comment]
Well, it's not meant only for localhost. One of the initial design goals was to keep system configuration/implementation out of the realm of concern of the client application. Having a constructor with a host in it exposes underlying implementation details, which I understand is useful for some use cases (particularly yours :D ) but I'm not sure we should commit to having that in the stable API yet. Not having it means we can do things like a server autodetection (zeroconf/bonjour, etc) and so on behind the scenes and have all client apps pick up on it.

I was thinking that we might have a companion library to ClientKit - maybe an ClientKitX - containing experimental APIs that aren't expected to be as commonly used and not the same api/abi stability efforts we'll have elsewhere, and that would be a decent place to try it out.

@yboger - do we have any game studio feedback on this point? (regarding configuration)

**Comment by janoc** [comment]
I quite fail to see how is a hostname/port a configuration - when I want to visit this website, I have also type github.com at some point (or use a bookmark, but that's a detail). Autodiscovery using Zeroconf or whatever cannot replace that. Honestly, I have yet to find a network-based application that does not allow specifying this somewhere.

IMO, a library should never impose design decisions like this on applications. It is up to the application whether or not they will always use the constructor without the host, constructor with the host and feed in "localhost" every time, load the host name from a configuration file/resource or use some sort of auto discovery mechanism or whatever. It is the application developer who knows best what their application needs, not the library/middleware vendor. The library is here to provide the tools I need to do my job, not to tell me how to manage my configuration system (which is a completely unrelated issue to managing input in an application). 

You can provide/support some recommended strategies and best practices, but that's all that the middleware should do. Libraries that try to impose policies like this are an enormous pain to use in the end, requiring hacks and workarounds to get the work done. 

You cannot anticipate every situation and need and are just constraining the usability of the library to a specific usage pattern. The mere existence of this issue here is actually the best evidence of that.

**Comment by janoc** [comment]
And re having a separate library - I could have actually implemented the change exactly like that. It was my first idea how to do it, so that I don't have to modify OSVR. It would have been also faster, because I wouldn't have needed to compile the Core. 

The reasons why I didn't do it like that in the end:
* It is an extra library that has to be loaded, deployed and consistency managed, especially as it needs low level/non-public APIs. That's a pain when dealing e.g. with Android, .NET wrappers, Unity, etc.
* Consistency - it would need a factory function creating the ClientContext when the hostname is needed. When it isn't needed, constructor can be used. Really ugly.
* It is a logical and straightforward extension of the existing ClientContext, especially when the low level code provides the functionality already.

**Comment by rpavlik** [comment]
Can you split this into two pull requests? (I could cherry-pick, but then we don't get a clean merge commit, etc) The localhost fix is a definite keeper, but I'd like to think/discuss some more on the other patch.

**Comment by janoc** [comment]
OK, here you go: 

Hostname enhancement #127 
https://github.com/OSVR/OSVR-Core/pull/154

Bugfix for the @localhost problem #139 
https://github.com/OSVR/OSVR-Core/pull/152

**Pull request closed without merging**
