### PR TITLE
Added updated display descriptors

### PR DESCRIPTION
**Pull request by rpavlik**
This solves #132 - I grabbed all the ones I could find and converted them (scripted, combo of `jq` and `sed`).  Note that we're right now splitting up the multi-resolution descriptors into single-resolution ones.

@yboger @DuFF14 If I could get a review of these and a clear to merge, that would be great.

### CODE REVIEW

**Comment by DuFF14** [comment]
Unity parser expects an integer for the rotate_180 field right now. Mentioned here as well: https://github.com/OSVR/OSVR-Unity/pull/46 
Some of these have an integer for this field (Vrvana, HMD.json), others have "true" or "false" (HDK, DK2). That is the only issue I noticed.

**Comment by rpavlik** [comment]
Hmm, so I assumed that it would do the conversions and that you were reading them as bools. I think it was my script that added them as "false" if they didn't already exists. Quite awkward as an integer, but since we're keeping the schema for now I can update that.

**Comment by rpavlik** [comment]
OK, re-ran the conversion script after changing the default to 0, and I've updated the schema, will be putting it in the repos. Can you test?

**Comment by DuFF14** [comment]
Vrvana is missing swap_eyes, num_displays, and note. Are these optional? Would default to swap_eyes=0 and num_displays = 1.
Tested with HDK and DK2. Looks good to merge.

**Comment by rpavlik** [comment]
If you want me to add those to all, I can, but I'd prefer to just let those default, particularly since num_displays is not long for this world...

**Comment by rpavlik** [comment]
And what is the `HMD.json` file? It looks like the HDK with less detail.

**Comment by DuFF14** [comment]
Yea I don't think it's necessary, just a template or default.

**Comment by DuFF14** [comment]
I don't have an issue with letting them default.

**Comment by rpavlik** [comment]
OK, will merge. I've pushed the associated schema to the schema repo and updated the submodule here too.

**Pull request merged**
